FROM ubuntu:26.04
LABEL org.opencontainers.image.authors="Vincent Chan <vichan39@buffalo.edu>"

ARG OCAML_VERSION=5.3.0

# Utility setup
RUN apt-get update
RUN apt-get install -y apt-utils build-essential
RUN apt-get install -y ca-certificates curl git python3 pipx
RUN apt-get install -y opam bubblewrap rsync unzip

# Install autodriver
WORKDIR /home
RUN useradd autolab
RUN useradd autograde
RUN mkdir autolab autograde output
RUN chown autolab:autolab autolab
RUN chown autolab:autolab output
RUN chown autograde:autograde autograde
RUN apt update && apt install -y sudo
RUN apt install -y git
RUN git clone https://github.com/autolab/Tango.git
WORKDIR Tango/autodriver
RUN make clean && make
RUN cp autodriver /usr/bin/autodriver
RUN chmod +s /usr/bin/autodriver

# OPAM Setup
WORKDIR /home/autograde
USER autograde
ENV PATH=/home/autograde/.opam/cse505/bin:$PATH
RUN opam init --bare -ay
RUN opam switch create cse505 ocaml-base-compiler.${OCAML_VERSION}
RUN opam install -y utop odoc ounit2 qcheck bisect_ppx menhir ocaml-lsp-server ocamlformat dune ppx_monad
RUN chmod +x .opam/opam-init/*.sh
RUN echo 'eval $(opam env)' >> .bashrc

# set up code analysis tool
ENV PATH=/home/autograde/.local/bin:$PATH
RUN pipx install semgrep

USER root
RUN echo "export PATH=/home/autograde/.opam/cse505/bin:$PATH" >> /etc/environment

# Clean up
RUN apt-get -y autoremove
RUN rm -rf Tango/
WORKDIR /home

# Check installation
RUN ls -l /home
USER autograde
RUN which autodriver
RUN which ocaml
RUN ocamlc --version
RUN dune --version
RUN python3 --version
RUN semgrep --version
USER root
